# Generated by Django 2.2.12 on 2022-02-24 02:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='discription',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
