# Generated by Django 2.2.12 on 2022-02-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20220224_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='status'),
        ),
    ]
